// Generated by Tiecode Development Platform - http://tiecode.cn
#include <jni.h>


// Origin: person.wangchen11.nativeview.接口类 按键事件
JNIEXPORT jboolean JNICALL Java_person_wangchen11_nativeview_NativeInterface_keyEvent(JNIEnv *env, jobject thiz, jint action, jint key) {
	vm_event(action, key, 0);
}


